In [17]:
from datasets import load_dataset

dataset = load_dataset("edinburghcstr/ami", "ihm")

Resolving data files:   0%|          | 0/42 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/42 [00:00<?, ?it/s]

Loading dataset shards:   0%|          | 0/36 [00:00<?, ?it/s]

In [21]:
dataset

DatasetDict({
    train: Dataset({
        features: ['meeting_id', 'audio_id', 'text', 'audio', 'begin_time', 'end_time', 'microphone_id', 'speaker_id'],
        num_rows: 108502
    })
    validation: Dataset({
        features: ['meeting_id', 'audio_id', 'text', 'audio', 'begin_time', 'end_time', 'microphone_id', 'speaker_id'],
        num_rows: 13098
    })
    test: Dataset({
        features: ['meeting_id', 'audio_id', 'text', 'audio', 'begin_time', 'end_time', 'microphone_id', 'speaker_id'],
        num_rows: 12643
    })
})

In [27]:
df = dataset["train"].select(range(5000)).to_pandas()
df.head()

,meeting_id,audio_id,text,audio,begin_time,end_time,microphone_id,speaker_id
0,EN2001a,AMI_EN2001a_H04_MEO069_0330297_0330718,IF YOU IF YOU S. S. H. AND THEY HAVE THIS BIG ...,{'bytes': b'RIFF\xb2\x1c\x04\x00WAVEfmt \x12\x...,3302.969971,3307.179932,H04,MEO069
1,EN2001a,AMI_EN2001a_H00_MEE068_0414915_0415078,I'VE GOTTEN MM HARDLY ANY,{'bytes': b'RIFF\xb2\x97\x01\x00WAVEfmt \x12\x...,4149.149902,4150.779785,H00,MEE068
2,EN2001a,AMI_EN2001a_H03_MEE067_0319290_0319815,IT'S YEAH I MEAN THE WAVE DATA ARE OBVIOUSLY N...,{'bytes': b'RIFF\xb2 \x05\x00WAVEfmt \x12\x00\...,3192.899902,3198.149902,H03,MEE067
3,EN2001a,AMI_EN2001a_H04_MEO069_0145515_0146152,YEAH IT'LL IT'LL PLAY THEM IN SOME ORDER IN WH...,{'bytes': b'RIFF\xb28\x06\x00WAVEfmt \x12\x00\...,1455.150024,1461.520020,H04,MEO069
4,EN2001a,AMI_EN2001a_H03_MEE067_0478127_0478164,YEAH,{'bytes': b'RIFF\xb2\\\x00\x00WAVEfmt \x12\x00...,4781.270020,4781.640137,H03,MEE067

In [28]:
dataset

DatasetDict({
    train: Dataset({
        features: ['meeting_id', 'audio_id', 'text', 'audio', 'begin_time', 'end_time', 'microphone_id', 'speaker_id'],
        num_rows: 108502
    })
    validation: Dataset({
        features: ['meeting_id', 'audio_id', 'text', 'audio', 'begin_time', 'end_time', 'microphone_id', 'speaker_id'],
        num_rows: 13098
    })
    test: Dataset({
        features: ['meeting_id', 'audio_id', 'text', 'audio', 'begin_time', 'end_time', 'microphone_id', 'speaker_id'],
        num_rows: 12643
    })
})

In [30]:
df.info()


df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   meeting_id     5000 non-null   str
 1   audio_id       5000 non-null   str
 2   text           5000 non-null   str
 3   audio          5000 non-null   object
 4   begin_time     5000 non-null   float32
 5   end_time       5000 non-null   float32
 6   microphone_id  5000 non-null   str
 7   speaker_id     5000 non-null   str
dtypes: float32(2), object(1), str(5)
memory usage: 770.1+ KB

,meeting_id,audio_id,text,audio,begin_time,end_time,microphone_id,speaker_id
count,5000,5000,5000,5000,5000.000000,5000.000000,5000,5000
unique,4,5000,3716,5000,NaN,NaN,5,5
top,EN2001a,AMI_EN2001a_H04_MEO069_0330297_0330718,YEAH,{'bytes': b'RIFF\xb2\x1c\x04\x00WAVEfmt \x12\x...,NaN,NaN,H01,MEO069
freq,1675,1,432,1,NaN,NaN,1740,2339
mean,NaN,NaN,NaN,NaN,2089.103027,2092.112549,NaN,NaN
std,NaN,NaN,NaN,NaN,1271.133057,1271.070923,NaN,NaN
min,NaN,NaN,NaN,NaN,0.020000,1.080000,NaN,NaN
25%,NaN,NaN,NaN,NaN,1026.440033,1027.892456,NaN,NaN
50%,NaN,NaN,NaN,NaN,1972.684998,1976.549988,NaN,NaN
75%,NaN,NaN,NaN,NaN,3014.644958,3017.542542,NaN,NaN
max,NaN,NaN,NaN,NaN,5132.140137,5132.569824,NaN,NaN